os:
  - linux
  - osx
  - windows

language: c

env:
  - BRANCH=1.0.2

cache:
  directories:
    - "$HOME/.choosenim"
    - "$TRAVIS_BUILD_DIR/git"

install:
  - export CHOOSENIM_NO_ANALYTICS=1
  - export PATH=`pwd`/git/bin:$HOME/.nimble/bin:$PATH
  - |
    if ! type -P choosenim &> /dev/null; then
      if [[ "$TRAVIS_OS_NAME" == "windows" ]]; then
        # Setup git outside "Program Files", space breaks cmake sh.exe
        mkdir git
        cd git
        curl -L -s "https://github.com/git-for-windows/git/releases/download/v2.23.0.windows.1/PortableGit-2.23.0-64-bit.7z.exe" -o portablegit.exe
        7z x -y -bd portablegit.exe
        cd ..

        # Latest choosenim binary doesn't have
        #   https://github.com/dom96/choosenim/pull/117
        #   https://github.com/dom96/choosenim/pull/135
        #
        # Using custom build with these PRs for Windows
        curl -L -s "https://bintray.com/genotrance/binaries/download_file?file_path=choosenim.exe" -o choosenim.exe
        curl -L -s "https://bintray.com/genotrance/binaries/download_file?file_path=libeay32.dll" -o libeay32.dll
        curl -L -s "https://bintray.com/genotrance/binaries/download_file?file_path=ssleay32.dll" -o ssleay32.dll
        ./choosenim.exe $BRANCH -y
        cp ./choosenim.exe $HOME/.nimble/bin/.
      else
        export CHOOSENIM_CHOOSE_VERSION=$BRANCH
        curl https://nim-lang.org/choosenim/init.sh -sSf > init.sh
        sh init.sh -y
      fi
    fi
  - |
    if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then
      # Work around https://github.com/nim-lang/Nim/issues/12337 fixed in 1.0+
      ulimit -n 8192
    fi

script:
  - nimble install -y -d
  - nim c src/choosenim
  - nimble test
  - yes | choosenim stable # Workaround tester overwriting our Nimble install.
  - nimble build -d:release
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then mv bin/choosenim bin/choosenim-linux; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then mv bin/choosenim bin/choosenim-osx; fi

notifications:
  irc: "chat.freenode.net#nimbuild"

deploy:
  provider: releases
  api_key:
    secure: "h7HQnn/pVHyR119IViY811WeX4lMl+hLpmMMND09r3LVOaH9MpMSkwQXa4aYF+/YV3vHaQINOExqTOXpzc/nP5O5VJMzfaEdA+o6HtkVgY1qsWllquUt0xnrvcFCLHcNQc/fwoS6Cow4yINsRTyGgo7p4zLnk5+yGSQTJiLTiMWHQiiRyCdrywBHFzcXG63MqRD7JJveA0OE/JoRNBNESGP6JTK6V7W2eanmlAjbjH8+dUJsxDr5LjoeRUUF+A+4AfulAOCsbPtURW3CIBD1jqYrFXzBYRgxbHaHwY5XxfPjHnWPHONYIruXx9oYyjL8uyrHzYSNCEnoQtBY0gzYOBFfUCNB3bcNDrSkzTXnRlnMcWcC6XyrTxUI7Lc+bZB5OFGoqYJzZK54qd5wmIDqZ+Wa2n1vq/hNfZ+95fYhG7oXgW/zeLWFdr8i46dRoBDfcD2e+OhJLk73FoGVwySffR2p5hCGWLdXFyMKiph1RC8JPiwMr4l6n9LmO1fbOwAjwTEXzj645mC1ExmsiTckGlOQC8UuvnxWg9xNggO40PCTuO64hF4YucDi6SzYttNn5VNli2XoWz9SkgQiKAxf4u2VN+S2Vt0Mtue8Z6CTb2GjEO+QrmVrW3oQmiCFM0LkiAo+0zoo8JK7PuT5EoAabfc0aZt/Ds8cLhPpoHQFxMY="
  file_glob: true
  file: bin/*
  skip_cleanup: true
  on:
    repo: dom96/choosenim
    tags: true
